# Generated by Django 5.1.3 on 2024-11-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='highscore',
            name='valid_game_id',
        ),
        migrations.AddConstraint(
            model_name='highscore',
            constraint=models.CheckConstraint(condition=models.Q(('game_id__in', [1, 2, 3])), name='valid_game_id'),
        ),
    ]
